apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "beskar.fullname" . }}-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ template "beskar.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  beskar.yaml: |-
{{ toYaml .Values.configData | indent 4 }}
