# Lint directives.
lint:

  # Linter rules.
  # Run `protolint list` to see all available rules.
  rules:
    # Determines whether or not to include the default set of linters.
    no_default: true

    # The specific linters to add.
    add:
      # Standard rules specified in: https://developers.google.com/protocol-buffers/docs/style
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - FILE_NAMES_LOWER_SNAKE_CASE
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - IMPORTS_SORTED
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - ORDER
      - PACKAGE_NAME_LOWER_CASE
      - RPC_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      # - MAX_LINE_LENGTH # Note(ikaneshiro): Ignoring because 80 char/wrapped lines will be an eyesore.
      - INDENT
      - PROTO3_FIELDS_AVOID_REQUIRED
      - PROTO3_GROUPS_AVOID
      # - REPEATED_FIELD_NAMES_PLURALIZED # Note(ikaneshiro): Ignoring because some repeated field names do not lend themselves to pluralization.
      - QUOTE_CONSISTENT

      # Others ... 
      - SERVICE_NAMES_END_WITH
      - SYNTAX_CONSISTENT
     

  # Linter rules option.
  rules_option:

    # INDENT rule option.
    indent:
      # Available styles are 4(4-spaces), 2(2-spaces) or tab.
      style: 2
      # Available newlines are "\n", "\r", or "\r\n".
      newline: "\n"

    # IMPORTS_SORTED rule option.
    imports_sorted:
      # Available newlines are "\n", "\r", or "\r\n".
      newline: "\n"

    # ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH rule option.
    enum_field_names_zero_value_end_with:
      suffix: UNSPECIFIED

    # SERVICE_NAMES_END_WITH rule option.
    service_names_end_with:
      text: Service

    # SYNTAX_CONSISTENT rule option.
    syntax_consistent:
      # Default is proto3.
      version: proto3
