name: beskar-ci
on:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: Run linters
        run: ./scripts/mage lint:all

  tests:
    name: tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: ./scripts/mage test:unit
      - name: Run integration tests
        run: ./scripts/mage test:integration

  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: Build binaries
        run: ./scripts/mage build:all
