name: release
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: Run linters
        run: ./scripts/mage lint:all

  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: Build binaries
        run: ./scripts/mage build:all

  release:
    name: release
    needs: [lint, build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: Release beskar image
        run: ./scripts/mage ci:image ghcr.io/ctrliq/beskar:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"
      - name: Release beskar helm chart
        run: ./scripts/mage ci:chart ghcr.io/ctrliq/helm-charts/beskar:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"
      - name: Release beskar-yum image
        run: ./scripts/mage ci:image ghcr.io/ctrliq/beskar-yum:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"
      - name: Release beskar-yum helm chart
        run: ./scripts/mage ci:chart ghcr.io/ctrliq/helm-charts/beskar-yum:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"