name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: Run linters
        run: ./scripts/mage lint:all

  tests:
    name: tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: ./scripts/mage test:unit
      - name: Run integration tests
        run: ./scripts/mage test:integration

  release-beskar:
    name: release beskar
    needs: [lint, tests]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: Release beskar image
        run: ./scripts/mage ci:image ghcr.io/ctrliq/beskar:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"
      - name: Release beskar helm chart
        run: ./scripts/mage ci:chart ghcr.io/ctrliq/helm-charts/beskar:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"

  release-beskar-yum:
    name: release beskar-yum
    needs: [lint, tests]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: Release beskar-yum image
        run: ./scripts/mage ci:image ghcr.io/ctrliq/beskar-yum:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"
      - name: Release beskar-yum helm chart
        run: ./scripts/mage ci:chart ghcr.io/ctrliq/helm-charts/beskar-yum:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"

  release-beskar-static:
    name: release beskar-static
    needs: [lint, tests]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: Release beskar-static image
        run: ./scripts/mage ci:image ghcr.io/ctrliq/beskar-static:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"
      - name: Release beskar-static helm chart
        run: ./scripts/mage ci:chart ghcr.io/ctrliq/helm-charts/beskar-static:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"

  release-beskar-ostree:
    name: release beskar-ostree
    needs: [lint, tests]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: actions/checkout@v3
      - name: Release beskar-ostree image
        run: ./scripts/mage ci:image ghcr.io/ctrliq/beskar-ostree:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"
      - name: Release beskar-ostree helm chart
        run: ./scripts/mage ci:chart ghcr.io/ctrliq/helm-charts/beskar-ostree:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"

  release-beskar-mirror:
    name: release beskar-mirror
    needs: [lint, tests]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: Release beskar-mirror image
        run: ./scripts/mage ci:image ghcr.io/ctrliq/beskar-mirror:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"
      - name: Release beskar-mirror helm chart
        run: ./scripts/mage ci:chart ghcr.io/ctrliq/helm-charts/beskar-mirror:${{ github.ref_name }} "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"